### ISSUE TITLE
nice rat

### ISSUE THREAD

**Issue by Soopyboo32** [NotEnoughFlips/NotEnoughFlips#1]

**Comment by RandomHumans** [comment]
just went through the code, there is no rat...

**Comment by Soopyboo32** [comment]
dont look at code on github lol
decompile the jar file given
![image](https://user-images.githubusercontent.com/49228220/152633396-d2e0d866-8ba8-49a5-9874-ae7dec7e197a.png)

**Comment by Soopyboo32** [comment]
lol
